version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    volumes:
        - postgres_data:/var/lib/postgresql/data/
        #- ./database/init.sql:/docker-entrypoint-initdb.d/1-schema.sql
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_INITDB_ARGS='--locale=tr_TR.UTF-8'
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"

volumes:
    postgres_data: